# Generated by Django 5.1.2 on 2024-11-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
