# Generated by Django 5.1.2 on 2024-11-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0005_alter_users_table_comment'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='users',
            table_comment=None,
        ),
    ]
