# Generated by Django 5.1.2 on 2024-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0006_alter_users_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
