# Generated by Django 5.1.2 on 2024-11-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0008_alter_users_table_comment_users_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetQuestionsConj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'question_set_questions_conj',
                'db_table_comment': '생성된 문제집 내역 - 문제 연결',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplates',
            fields=[
                ('question_id', models.CharField(db_comment='문제 번호 최대 5자리 숫자와 최대 6자의 조합. 예;25876_160952', max_length=20, primary_key=True, serialize=False)),
                ('question_grade', models.CharField(blank=True, db_comment='문제 학년 (예: P3~P6, M1~M3, H)', max_length=10, null=True)),
                ('question_term', models.IntegerField(blank=True, db_comment='문제 학기 (1 또는 2)', null=True)),
                ('question_unit', models.CharField(blank=True, db_comment='문제 단원 (01~99)', max_length=10, null=True)),
                ('question_topic', models.IntegerField(blank=True, db_comment='문제 토픽 주제 (1~999999)', null=True)),
                ('question_topic_name', models.CharField(blank=True, db_comment='토픽명 텍스트', max_length=255, null=True)),
                ('question_type1', models.CharField(blank=True, db_comment='문제 유형1 (단답형, 선택형)', max_length=10, null=True)),
                ('question_type2', models.IntegerField(blank=True, db_comment='발문 구성 유형 (1: 자료+질문, 2: 단일질문)', null=True)),
                ('question_condition', models.IntegerField(blank=True, db_comment='풀이 필수 조건 (0: 없음, 1: 있음)', null=True)),
                ('question_step', models.CharField(blank=True, db_comment='학습 단계 (기본/실생활 활용)', max_length=10, null=True)),
                ('question_sector1', models.CharField(blank=True, db_comment='평가 영역1 (예: 계산/이해/추론/문제해결)', max_length=10, null=True)),
                ('question_sector2', models.CharField(blank=True, db_comment='내용 영역 (예: 수와 연산, 도형과 측정, 변화와 관계, 자료와 가능성)', max_length=255, null=True)),
                ('question_difficulty', models.IntegerField(blank=True, db_comment='출제 난이도 (1: 상, 2: 중, 3: 하)', null=True)),
                ('question_contents', models.IntegerField(blank=True, db_comment='그림 자료 필요 여부 (0: 없음, 1: 있음)', null=True)),
                ('figure_text', models.TextField(blank=True, db_comment='도형 설명 텍스트 (optional)', null=True)),
                ('question_text', models.TextField(blank=True, db_comment='문제 텍스트', null=True)),
                ('source', models.CharField(blank=True, db_comment='데이터 출처', max_length=255, null=True)),
            ],
            options={
                'db_table': 'question_templates',
                'db_table_comment': '문제 템플릿',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersQuestionSetConj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set_status', models.IntegerField(db_comment='문제집 상태(1: generating, 2:ready, 3:completed)')),
            ],
            options={
                'db_table': 'users_question_set_conj',
                'db_table_comment': '사용자 - 생성된 문제집 내역 연결',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='next_question_set_id',
            field=models.CharField(blank=True, db_comment='다음 문제집 번호', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='next_question_set_ready',
            field=models.BooleanField(blank=True, db_comment='다음 문제집 준비 여부', null=True),
        ),
    ]
