# Generated by Django 5.1.2 on 2024-11-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0009_questionsetquestionsconj_questiontemplates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='next_question_set_id',
            field=models.IntegerField(blank=True, db_comment='다음 문제집 번호', null=True),
        ),
    ]
