# Generated by Django 5.1.2 on 2024-11-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0010_alter_users_next_question_set_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsetquestionsconj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersquestionsetconj',
            options={'managed': True},
        ),
    ]
