# Generated by Django 5.1.2 on 2024-11-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0011_alter_questionsetquestionsconj_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsetquestionsconj',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersquestionsetconj',
            options={'managed': False},
        ),
    ]
