# Generated by Django 5.1.2 on 2024-11-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4ds', '0013_alter_questionsetquestionsconj_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsetquestionsconj',
            options={'managed': False},
        ),
    ]
